### ISSUE TITLE
Word Formation flow starts with a CellRenderer error in iOS and Android

### ISSUE THREAD

**Issue by nsinghGH** [jaspal27/UCPunjabi#8]
Starting Word Formation flow after a fresh app launch results in this error seen in metro shell.

[Wed Jan 06 2021 12:47:33.159]  ERROR    Warning: Failed child context type: Invalid child context `virtualizedCell.cellKey` of type `number` supplied to `CellRenderer`, expected `string`.
    in CellRenderer (at VirtualizedList.js:900)
    in RCTScrollContentView (at ScrollView.js:1124)
    in RCTScrollView (at ScrollView.js:1260)
    in ScrollView (at ScrollView.js:1286)
    in ScrollView (at VirtualizedList.js:1329)
    in VirtualizedList (at FlatList.js:624)
    in FlatList (at WordFormation/index.tsx:122)
    in RCTView (at View.js:34)
    in View (at WordFormation/index.tsx:106)
    in WordFormation (at SceneView.tsx:122)

See screenshots for details:
![ios-WF1-start-error](https://user-images.githubusercontent.com/14082194/103822331-c50de900-5024-11eb-9e55-c52752b76d75.png)
![ios-WF1-start-error-details](https://user-images.githubusercontent.com/14082194/103822339-c8a17000-5024-11eb-8b87-65dba91a4d03.png)

**Comment by jaspal27** [comment]
fixed
